# Generated by Django 4.1.3 on 2022-12-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
